'use client';

import ReactMarkdown from 'react-markdown';

type CVPreviewProps = {
  cvContent: string;
  onAnalyze: () => void;
  onEdit: () => void;
  isAnalyzing?: boolean;
};

export default function CVPreview({
  cvContent,
  onAnalyze,
  onEdit,
  isAnalyzing = false,
}: CVPreviewProps) {
  const handleDownload = () => {
    const blob = new Blob([cvContent], { type: 'text/markdown;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `CV_${new Date().getTime()}.md`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(cvContent);
      alert('CV berhasil di-copy! Paste di Word/Google Docs ya.');
    } catch (error) {
      alert('Gagal copy. Coba lagi ya.');
    }
  };

  return (
    <div className="mt-6 bg-white rounded-2xl shadow-lg border border-gray-200 overflow-hidden">
      {/* HEADER */}
      <div className="bg-gradient-to-r from-indigo-600 to-pink-600 px-6 py-4 flex items-center justify-between">
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 bg-white/20 rounded-lg flex items-center justify-center">
            <svg className="w-6 h-6 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
            </svg>
          </div>
          <div>
            <h2 className="font-bold text-white text-lg">CV Preview</h2>
            <p className="text-xs text-indigo-100">Generated by AI</p>
          </div>
        </div>

        <button
          onClick={onEdit}
          disabled={isAnalyzing}
          className="text-white/80 hover:text-white text-sm font-medium flex items-center gap-1 transition disabled:opacity-50 disabled:cursor-not-allowed"
          title="Edit CV"
        >
          <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z" />
          </svg>
          Edit
        </button>
      </div>

      {/* CV CONTENT */}
      <div className="px-6 py-8 max-h-[600px] overflow-y-auto">
        <article className="prose prose-sm max-w-none prose-headings:text-gray-900 prose-h1:text-3xl prose-h1:font-bold prose-h1:mb-1 prose-h2:text-lg prose-h2:font-bold prose-h2:text-indigo-600 prose-h2:border-b prose-h2:border-gray-200 prose-h2:pb-1 prose-h2:mt-6 prose-p:text-gray-700 prose-strong:text-gray-900 prose-ul:my-2 prose-li:text-gray-700 prose-li:my-0">
          <ReactMarkdown>{cvContent}</ReactMarkdown>
        </article>
      </div>

      {/* ACTION BUTTONS */}
      <div className="px-6 py-4 bg-gray-50 border-t border-gray-200 flex flex-wrap gap-2">
        {/* Primary CTA: Analyze with loading state */}
        <button
          onClick={onAnalyze}
          disabled={isAnalyzing}
          className="flex-1 min-w-[180px] bg-gradient-to-r from-indigo-600 to-pink-600 hover:opacity-90 text-white px-4 py-3 rounded-xl font-semibold flex items-center justify-center gap-2 transition shadow-md disabled:opacity-70 disabled:cursor-not-allowed"
        >
          {isAnalyzing ? (
            <>
              <svg className="w-5 h-5 animate-spin" fill="none" viewBox="0 0 24 24">
                <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
                <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z" />
              </svg>
              Menganalisis...
            </>
          ) : (
            <>
              <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 10V3L4 14h7v7l9-11h-7z" />
              </svg>
              Analisis Karir
            </>
          )}
        </button>

        <button
          onClick={handleDownload}
          disabled={isAnalyzing}
          className="flex-1 min-w-[140px] bg-white hover:bg-gray-50 border-2 border-gray-200 hover:border-indigo-300 text-gray-700 px-4 py-3 rounded-xl font-semibold flex items-center justify-center gap-2 transition disabled:opacity-50 disabled:cursor-not-allowed"
        >
          <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
          </svg>
          Download
        </button>

        <button
          onClick={handleCopy}
          disabled={isAnalyzing}
          className="flex-1 min-w-[120px] bg-white hover:bg-gray-50 border-2 border-gray-200 hover:border-indigo-300 text-gray-700 px-4 py-3 rounded-xl font-semibold flex items-center justify-center gap-2 transition disabled:opacity-50 disabled:cursor-not-allowed"
        >
          <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z" />
          </svg>
          Copy
        </button>
      </div>
    </div>
  );
}